name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4.5.0
    #   with:
    #     name: artifact
    #     path: target/release/your_executable # 替换为实际的可执行文件路径
    #     if-no-files-found: warn
    #     compression-level: 6
    #     overwrite: false
    #     include-hidden-files: false

